root_path = "C:/Sync/namsor Dropbox/Elian CARSENAT/0_Coprophet/8_HackathonVersailles/CommerçantsConfidentiel/"
opendata_path = "C:/Sync/namsor Dropbox/Elian CARSENAT/0_Coprophet/8_HackathonVersailles/CommerçantsOpenData/"
git_path = "C:/git/202502_versailles_sept_lieux/data/processed/"
date_split_train = '2024-12-01'
date_split_valid = '2024-12-15'
date_split_test = '2024-12-31'
field_date = 'date'
field_y = 'y_value'
field_seriesname = 'series_name'
field_train_valid_test = 'train_valid_test'
